package th.ac.ku.kps.eng.cpe.se.model;
// Generated Mar 31, 2023, 10:36:07 PM by Hibernate Tools 6.1.5.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Agency generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Agency implements java.io.Serializable {

	private Integer idAgency;
	private String nameAgency;
	private String addressAgency;
	private String status;
	private String phone;
	@JsonIgnore private Set appoves = new HashSet(0);
	@JsonIgnore private Set projects = new HashSet(0);
	@JsonIgnore private Set managers = new HashSet(0);

	public Agency() {
	}

	public Agency(String nameAgency, String addressAgency, String status, String phone) {
		this.nameAgency = nameAgency;
		this.addressAgency = addressAgency;
		this.status = status;
		this.phone = phone;
	}

	public Agency(String nameAgency, String addressAgency, String status, String phone, Set appoves, Set projects,
			Set managers) {
		this.nameAgency = nameAgency;
		this.addressAgency = addressAgency;
		this.status = status;
		this.phone = phone;
		this.appoves = appoves;
		this.projects = projects;
		this.managers = managers;
	}

	public Integer getIdAgency() {
		return this.idAgency;
	}

	public void setIdAgency(Integer idAgency) {
		this.idAgency = idAgency;
	}

	public String getNameAgency() {
		return this.nameAgency;
	}

	public void setNameAgency(String nameAgency) {
		this.nameAgency = nameAgency;
	}

	public String getAddressAgency() {
		return this.addressAgency;
	}

	public void setAddressAgency(String addressAgency) {
		this.addressAgency = addressAgency;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Set getAppoves() {
		return this.appoves;
	}

	public void setAppoves(Set appoves) {
		this.appoves = appoves;
	}

	public Set getProjects() {
		return this.projects;
	}

	public void setProjects(Set projects) {
		this.projects = projects;
	}

	public Set getManagers() {
		return this.managers;
	}

	public void setManagers(Set managers) {
		this.managers = managers;
	}

}
