package th.ac.ku.kps.eng.cpe.se.model;
// Generated Mar 31, 2023, 10:36:07 PM by Hibernate Tools 6.1.5.Final

import java.sql.Date;

/**
 * Appove generated by hbm2java
 */
public class Appove implements java.io.Serializable {

	private Integer idAppoveAgency;
	private Project project;
	private Agency agency;
	private User userByIdApprover;
	private User userByIdUser;
	private Date dateAppove;
	private String description;
	private String type;
	private String evidence;

	public Appove() {
	}

	public Appove(Date dateAppove, String description, String type, String evidence) {
		this.dateAppove = dateAppove;
		this.description = description;
		this.type = type;
		this.evidence = evidence;
	}
	
	public Appove(Agency agency,User userByIdUser, Date dateAppove,String description, String type, String evidence) {
		this.userByIdUser = userByIdUser;
		this.agency = agency;
		this.dateAppove = dateAppove;
		this.description = description;
		this.type = type;
		this.evidence = evidence;
	}
	
	public Appove(User userByIdUser, Date dateAppove,String description, String type, String evidence) {
		this.userByIdUser = userByIdUser;
		this.dateAppove = dateAppove;
		this.description = description;
		this.type = type;
		this.evidence = evidence;
	}

	public Appove(Project project, Agency agency, User userByIdApprover, User userByIdUser, Date dateAppove,
			String description, String type, String evidence) {
		this.project = project;
		this.agency = agency;
		this.userByIdApprover = userByIdApprover;
		this.userByIdUser = userByIdUser;
		this.dateAppove = dateAppove;
		this.description = description;
		this.type = type;
		this.evidence = evidence;
	}

	public Integer getIdAppoveAgency() {
		return this.idAppoveAgency;
	}

	public void setIdAppoveAgency(Integer idAppoveAgency) {
		this.idAppoveAgency = idAppoveAgency;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public Agency getAgency() {
		return this.agency;
	}

	public void setAgency(Agency agency) {
		this.agency = agency;
	}

	public User getUserByIdApprover() {
		return this.userByIdApprover;
	}

	public void setUserByIdApprover(User userByIdApprover) {
		this.userByIdApprover = userByIdApprover;
	}

	public User getUserByIdUser() {
		return this.userByIdUser;
	}

	public void setUserByIdUser(User userByIdUser) {
		this.userByIdUser = userByIdUser;
	}

	public Date getDateAppove() {
		return this.dateAppove;
	}

	public void setDateAppove(Date dateAppove) {
		this.dateAppove = dateAppove;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getEvidence() {
		return this.evidence;
	}

	public void setEvidence(String evidence) {
		this.evidence = evidence;
	}

}
