package th.ac.ku.kps.eng.cpe.se.model;
// Generated Mar 31, 2023, 10:36:07 PM by Hibernate Tools 6.1.5.Final

/**
 * AppoveProject generated by hbm2java
 */
public class AppoveProject implements java.io.Serializable {

	private AppoveProjectId id;

	public AppoveProject() {
	}

	public AppoveProject(AppoveProjectId id) {
		this.id = id;
	}

	public AppoveProjectId getId() {
		return this.id;
	}

	public void setId(AppoveProjectId id) {
		this.id = id;
	}

}
