package th.ac.ku.kps.eng.cpe.se.model;
// Generated Mar 31, 2023, 10:36:07 PM by Hibernate Tools 6.1.5.Final

import java.sql.Date;

/**
 * AppoveProjectId generated by hbm2java
 */
public class AppoveProjectId implements java.io.Serializable {

	private Date dateAppove;
	private String description;
	private int idAppoveProject;
	private String idApprover;
	private int idProject;
	private int idUser;

	public AppoveProjectId() {
	}

	public AppoveProjectId(Date dateAppove, String description, int idAppoveProject, String idApprover, int idProject,
			int idUser) {
		this.dateAppove = dateAppove;
		this.description = description;
		this.idAppoveProject = idAppoveProject;
		this.idApprover = idApprover;
		this.idProject = idProject;
		this.idUser = idUser;
	}

	public Date getDateAppove() {
		return this.dateAppove;
	}

	public void setDateAppove(Date dateAppove) {
		this.dateAppove = dateAppove;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getIdAppoveProject() {
		return this.idAppoveProject;
	}

	public void setIdAppoveProject(int idAppoveProject) {
		this.idAppoveProject = idAppoveProject;
	}

	public String getIdApprover() {
		return this.idApprover;
	}

	public void setIdApprover(String idApprover) {
		this.idApprover = idApprover;
	}

	public int getIdProject() {
		return this.idProject;
	}

	public void setIdProject(int idProject) {
		this.idProject = idProject;
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AppoveProjectId))
			return false;
		AppoveProjectId castOther = (AppoveProjectId) other;

		return ((this.getDateAppove() == castOther.getDateAppove()) || (this.getDateAppove() != null
				&& castOther.getDateAppove() != null && this.getDateAppove().equals(castOther.getDateAppove())))
				&& ((this.getDescription() == castOther.getDescription())
						|| (this.getDescription() != null && castOther.getDescription() != null
								&& this.getDescription().equals(castOther.getDescription())))
				&& (this.getIdAppoveProject() == castOther.getIdAppoveProject())
				&& ((this.getIdApprover() == castOther.getIdApprover()) || (this.getIdApprover() != null
						&& castOther.getIdApprover() != null && this.getIdApprover().equals(castOther.getIdApprover())))
				&& (this.getIdProject() == castOther.getIdProject()) && (this.getIdUser() == castOther.getIdUser());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDateAppove() == null ? 0 : this.getDateAppove().hashCode());
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		result = 37 * result + this.getIdAppoveProject();
		result = 37 * result + (getIdApprover() == null ? 0 : this.getIdApprover().hashCode());
		result = 37 * result + this.getIdProject();
		result = 37 * result + this.getIdUser();
		return result;
	}

}
