package th.ac.ku.kps.eng.cpe.se.model;
// Generated Mar 31, 2023, 10:36:07 PM by Hibernate Tools 6.1.5.Final

import java.sql.Date;

/**
 * DonateDetail generated by hbm2java
 */
public class DonateDetail implements java.io.Serializable {

	private Integer idDonateDetail;
	private Donate donate;
	private User user;
	private String accountName;
	private int amount;
	private Date dateDonate;
	private String evidenceDonate;
	private String statusAppove;

	public DonateDetail() {
	}

	public DonateDetail(Donate donate, User user, String accountName, int amount, Date dateDonate,
			String evidenceDonate, String statusAppove) {
		this.donate = donate;
		this.user = user;
		this.accountName = accountName;
		this.amount = amount;
		this.dateDonate = dateDonate;
		this.evidenceDonate = evidenceDonate;
		this.statusAppove = statusAppove;
	}

	public Integer getIdDonateDetail() {
		return this.idDonateDetail;
	}

	public void setIdDonateDetail(Integer idDonateDetail) {
		this.idDonateDetail = idDonateDetail;
	}

	public Donate getDonate() {
		return this.donate;
	}

	public void setDonate(Donate donate) {
		this.donate = donate;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public Date getDateDonate() {
		return this.dateDonate;
	}

	public void setDateDonate(Date dateDonate) {
		this.dateDonate = dateDonate;
	}

	public String getEvidenceDonate() {
		return this.evidenceDonate;
	}

	public void setEvidenceDonate(String evidenceDonate) {
		this.evidenceDonate = evidenceDonate;
	}

	public String getStatusAppove() {
		return this.statusAppove;
	}

	public void setStatusAppove(String statusAppove) {
		this.statusAppove = statusAppove;
	}

}
