package th.ac.ku.kps.eng.cpe.se.model;
// Generated Mar 31, 2023, 10:36:07 PM by Hibernate Tools 6.1.5.Final

/**
 * FollowProject generated by hbm2java
 */
public class FollowProject implements java.io.Serializable {

	private Integer idFollow;
	private Project project;
	private User user;

	public FollowProject() {
	}

	public FollowProject(Project project, User user) {
		this.project = project;
		this.user = user;
	}

	public Integer getIdFollow() {
		return this.idFollow;
	}

	public void setIdFollow(Integer idFollow) {
		this.idFollow = idFollow;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
