package th.ac.ku.kps.eng.cpe.se.model;
// Generated Mar 31, 2023, 10:36:07 PM by Hibernate Tools 6.1.5.Final

import java.sql.Time;

/**
 * JoinerProject generated by hbm2java
 */
public class JoinerProject implements java.io.Serializable {

	private Integer idJoiner;
	private int idTaskProject;
	private String idUser;
	private int numberUser;
	private int scoreDistance;
	private Time scoreTime;

	public JoinerProject() {
	}

	public JoinerProject(int idTaskProject, String idUser, int numberUser, int scoreDistance, Time scoreTime) {
		this.idTaskProject = idTaskProject;
		this.idUser = idUser;
		this.numberUser = numberUser;
		this.scoreDistance = scoreDistance;
		this.scoreTime = scoreTime;
	}

	public Integer getIdJoiner() {
		return this.idJoiner;
	}

	public void setIdJoiner(Integer idJoiner) {
		this.idJoiner = idJoiner;
	}

	public int getIdTaskProject() {
		return this.idTaskProject;
	}

	public void setIdTaskProject(int idTaskProject) {
		this.idTaskProject = idTaskProject;
	}

	public String getIdUser() {
		return this.idUser;
	}

	public void setIdUser(String idUser) {
		this.idUser = idUser;
	}

	public int getNumberUser() {
		return this.numberUser;
	}

	public void setNumberUser(int numberUser) {
		this.numberUser = numberUser;
	}

	public int getScoreDistance() {
		return this.scoreDistance;
	}

	public void setScoreDistance(int scoreDistance) {
		this.scoreDistance = scoreDistance;
	}

	public Time getScoreTime() {
		return this.scoreTime;
	}

	public void setScoreTime(Time scoreTime) {
		this.scoreTime = scoreTime;
	}

}
