package th.ac.ku.kps.eng.cpe.se.model;
// Generated Mar 31, 2023, 10:36:07 PM by Hibernate Tools 6.1.5.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Manager generated by hbm2java
 */
public class Manager implements java.io.Serializable {

	private Integer idManager;
	private Agency agency;
	private User user;
	@JsonIgnore private Set managerProjects = new HashSet(0);

	public Manager() {
	}

	public Manager(User user) {
		this.user = user;
	}

	public Manager(Agency agency, User user, Set managerProjects) {
		this.agency = agency;
		this.user = user;
		this.managerProjects = managerProjects;
	}
	public Manager(Agency agency, User user) {
		this.agency = agency;
		this.user = user;
	}

	public Integer getIdManager() {
		return this.idManager;
	}

	public void setIdManager(Integer idManager) {
		this.idManager = idManager;
	}

	public Agency getAgency() {
		return this.agency;
	}

	public void setAgency(Agency agency) {
		this.agency = agency;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Set getManagerProjects() {
		return this.managerProjects;
	}

	public void setManagerProjects(Set managerProjects) {
		this.managerProjects = managerProjects;
	}

}
