package th.ac.ku.kps.eng.cpe.se.model;
// Generated Mar 31, 2023, 10:36:07 PM by Hibernate Tools 6.1.5.Final

/**
 * ManagerAgency generated by hbm2java
 */
public class ManagerAgency implements java.io.Serializable {

	private Integer idManagerAcency;
	private int idAgency;
	private String idUser;

	public ManagerAgency() {
	}

	public ManagerAgency(int idAgency, String idUser) {
		this.idAgency = idAgency;
		this.idUser = idUser;
	}

	public Integer getIdManagerAcency() {
		return this.idManagerAcency;
	}

	public void setIdManagerAcency(Integer idManagerAcency) {
		this.idManagerAcency = idManagerAcency;
	}

	public int getIdAgency() {
		return this.idAgency;
	}

	public void setIdAgency(int idAgency) {
		this.idAgency = idAgency;
	}

	public String getIdUser() {
		return this.idUser;
	}

	public void setIdUser(String idUser) {
		this.idUser = idUser;
	}

}
