package th.ac.ku.kps.eng.cpe.se.model;
// Generated Mar 31, 2023, 10:36:07 PM by Hibernate Tools 6.1.5.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * Project generated by hbm2java
 */
@JsonIdentityInfo(
	    generator = ObjectIdGenerators.PropertyGenerator.class,
	    property = "idProject"
	)
public class Project implements java.io.Serializable {

	private Integer idProject;
	private Agency agency;
	private String nameProject;
	private Date dateStart;
	private Date dateEnd;
	private String phone;
	private String addressProject;
	private String status;
	private int idProvince;
	private Date dateRegisStart;
	private Date dateRegisEnd;
	private String discription;
	private String imagePofile;
	private String imagePoster;
	@JsonIgnore private Set appoves = new HashSet(0);
	@JsonIgnore private Set taskProjects = new HashSet(0);
	@JsonIgnore private Set managerProjects = new HashSet(0);
	private Set followProjects = new HashSet(0);
	private Set donates = new HashSet(0);

	public Project() {
	}

	public Project(Agency agency, String nameProject, Date dateStart, Date dateEnd, String phone, String addressProject,
			String status, int idProvince, Date dateRegisStart, Date dateRegisEnd, String discription) {
		this.agency = agency;
		this.nameProject = nameProject;
		this.dateStart = dateStart;
		this.dateEnd = dateEnd;
		this.phone = phone;
		this.addressProject = addressProject;
		this.status = status;
		this.idProvince = idProvince;
		this.dateRegisStart = dateRegisStart;
		this.dateRegisEnd = dateRegisEnd;
		this.discription = discription;
	}

	public Project(Agency agency, String nameProject, Date dateStart, Date dateEnd, String phone, String addressProject,
			String status, int idProvince, Date dateRegisStart, Date dateRegisEnd, String discription,
			String imagePofile, String imagePoster, Set appoves, Set taskProjects, Set managerProjects,
			Set followProjects, Set donates) {
		this.agency = agency;
		this.nameProject = nameProject;
		this.dateStart = dateStart;
		this.dateEnd = dateEnd;
		this.phone = phone;
		this.addressProject = addressProject;
		this.status = status;
		this.idProvince = idProvince;
		this.dateRegisStart = dateRegisStart;
		this.dateRegisEnd = dateRegisEnd;
		this.discription = discription;
		this.imagePofile = imagePofile;
		this.imagePoster = imagePoster;
		this.appoves = appoves;
		this.taskProjects = taskProjects;
		this.managerProjects = managerProjects;
		this.followProjects = followProjects;
		this.donates = donates;
	}
	
	public Project(Agency agency, String nameProject, Date dateStart, Date dateEnd, String phone, String addressProject,
			String status, int idProvince, Date dateRegisStart, Date dateRegisEnd, String discription,
			String imagePofile, String imagePoster) {
		this.agency = agency;
		this.nameProject = nameProject;
		this.dateStart = dateStart;
		this.dateEnd = dateEnd;
		this.phone = phone;
		this.addressProject = addressProject;
		this.status = status;
		this.idProvince = idProvince;
		this.dateRegisStart = dateRegisStart;
		this.dateRegisEnd = dateRegisEnd;
		this.discription = discription;
		this.imagePofile = imagePofile;
		this.imagePoster = imagePoster;

	}
	public Integer getIdProject() {
		return this.idProject;
	}

	public void setIdProject(Integer idProject) {
		this.idProject = idProject;
	}

	public Agency getAgency() {
		return this.agency;
	}

	public void setAgency(Agency agency) {
		this.agency = agency;
	}

	public String getNameProject() {
		return this.nameProject;
	}

	public void setNameProject(String nameProject) {
		this.nameProject = nameProject;
	}

	public Date getDateStart() {
		return this.dateStart;
	}

	public void setDateStart(Date dateStart) {
		this.dateStart = dateStart;
	}

	public Date getDateEnd() {
		return this.dateEnd;
	}

	public void setDateEnd(Date dateEnd) {
		this.dateEnd = dateEnd;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddressProject() {
		return this.addressProject;
	}

	public void setAddressProject(String addressProject) {
		this.addressProject = addressProject;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public int getIdProvince() {
		return this.idProvince;
	}

	public void setIdProvince(int idProvince) {
		this.idProvince = idProvince;
	}

	public Date getDateRegisStart() {
		return this.dateRegisStart;
	}

	public void setDateRegisStart(Date dateRegisStart) {
		this.dateRegisStart = dateRegisStart;
	}

	public Date getDateRegisEnd() {
		return this.dateRegisEnd;
	}

	public void setDateRegisEnd(Date dateRegisEnd) {
		this.dateRegisEnd = dateRegisEnd;
	}

	public String getDiscription() {
		return this.discription;
	}

	public void setDiscription(String discription) {
		this.discription = discription;
	}

	public String getImagePofile() {
		return this.imagePofile;
	}

	public void setImagePofile(String imagePofile) {
		this.imagePofile = imagePofile;
	}

	public String getImagePoster() {
		return this.imagePoster;
	}

	public void setImagePoster(String imagePoster) {
		this.imagePoster = imagePoster;
	}

	public Set getAppoves() {
		return this.appoves;
	}

	public void setAppoves(Set appoves) {
		this.appoves = appoves;
	}

	public Set getTaskProjects() {
		return this.taskProjects;
	}

	public void setTaskProjects(Set taskProjects) {
		this.taskProjects = taskProjects;
	}

	public Set getManagerProjects() {
		return this.managerProjects;
	}

	public void setManagerProjects(Set managerProjects) {
		this.managerProjects = managerProjects;
	}

	public Set getFollowProjects() {
		return this.followProjects;
	}

	public void setFollowProjects(Set followProjects) {
		this.followProjects = followProjects;
	}

	public Set getDonates() {
		return this.donates;
	}

	public void setDonates(Set donates) {
		this.donates = donates;
	}

}
