package th.ac.ku.kps.eng.cpe.se.model;
// Generated Mar 31, 2023, 10:36:07 PM by Hibernate Tools 6.1.5.Final

import java.sql.Date;

/**
 * RegisterProject generated by hbm2java
 */
public class RegisterProject implements java.io.Serializable {

	private Integer idRegister;
	private TaskProject taskProject;
	private User user;
	private Date dateRegister;
	private String evidenceRegister;
	private int numberRunner;
	private String status;

	public RegisterProject() {
	}

	public RegisterProject(TaskProject taskProject, User user, Date dateRegister, String evidenceRegister,
			int numberRunner, String status) {
		this.taskProject = taskProject;
		this.user = user;
		this.dateRegister = dateRegister;
		this.evidenceRegister = evidenceRegister;
		this.numberRunner = numberRunner;
		this.status = status;
	}

	public Integer getIdRegister() {
		return this.idRegister;
	}

	public void setIdRegister(Integer idRegister) {
		this.idRegister = idRegister;
	}

	public TaskProject getTaskProject() {
		return this.taskProject;
	}

	public void setTaskProject(TaskProject taskProject) {
		this.taskProject = taskProject;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getDateRegister() {
		return this.dateRegister;
	}

	public void setDateRegister(Date dateRegister) {
		this.dateRegister = dateRegister;
	}

	public String getEvidenceRegister() {
		return this.evidenceRegister;
	}

	public void setEvidenceRegister(String evidenceRegister) {
		this.evidenceRegister = evidenceRegister;
	}

	public int getNumberRunner() {
		return this.numberRunner;
	}

	public void setNumberRunner(int numberRunner) {
		this.numberRunner = numberRunner;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
