package th.ac.ku.kps.eng.cpe.se.model;
// Generated Mar 31, 2023, 10:36:07 PM by Hibernate Tools 6.1.5.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * TaskProject generated by hbm2java
 */
public class TaskProject implements java.io.Serializable {

	private Integer idTaskProject;
	private Project project;
	private String taskName;
	private int priceTask;
	private int distance;
	private int limitJoin;
	@JsonIgnore private Set registerProjects = new HashSet(0);

	public TaskProject() {
	}

	public TaskProject(Project project, String taskName, int priceTask, int distance, int limitJoin) {
		this.project = project;
		this.taskName = taskName;
		this.priceTask = priceTask;
		this.distance = distance;
		this.limitJoin = limitJoin;
	}

	public TaskProject(Project project, String taskName, int priceTask, int distance, int limitJoin,
			Set registerProjects) {
		this.project = project;
		this.taskName = taskName;
		this.priceTask = priceTask;
		this.distance = distance;
		this.limitJoin = limitJoin;
		this.registerProjects = registerProjects;
	}

	public Integer getIdTaskProject() {
		return this.idTaskProject;
	}

	public void setIdTaskProject(Integer idTaskProject) {
		this.idTaskProject = idTaskProject;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	public int getPriceTask() {
		return this.priceTask;
	}

	public void setPriceTask(int priceTask) {
		this.priceTask = priceTask;
	}

	public int getDistance() {
		return this.distance;
	}

	public void setDistance(int distance) {
		this.distance = distance;
	}

	public int getLimitJoin() {
		return this.limitJoin;
	}

	public void setLimitJoin(int limitJoin) {
		this.limitJoin = limitJoin;
	}

	public Set getRegisterProjects() {
		return this.registerProjects;
	}

	public void setRegisterProjects(Set registerProjects) {
		this.registerProjects = registerProjects;
	}

}
