package th.ac.ku.kps.eng.cpe.se.model;
// Generated Mar 31, 2023, 10:36:07 PM by Hibernate Tools 6.1.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.validation.constraints.Email;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * User generated by hbm2java
 */
@JsonIdentityInfo(
	    generator = ObjectIdGenerators.PropertyGenerator.class,
	    property = "idUser"
	)
public class User implements java.io.Serializable {
	
	@NotBlank(message = "Invalid User ID: Empty User ID")
	@Size(min = 3, max = 20, message = "Invalid User ID: Must be of 3 - 20 characters")
	private String idUser;
	@NotBlank(message = "Invalid Firstname: Empty Firstname")
	@Size(min = 3, max = 20, message = "Invalid firstname: Must be of 3 - 20 characters")
	private String fristName;
	@NotBlank(message = "Invalid Password: Empty Password")
	@Size(min = 8, max = 15, message = "Invalid Password: Must be of 8 - 15 characters")
	private String password;
	@Min(value = 5, message = "You must be at least 5 years old to register.")
	@Max(value = 120, message = "You cannot be more than 120 years old.")
	private int age;
	@NotBlank(message = "Invalid Address: Empty Address")
	private String address;
	@Pattern(regexp = "\\d{10}", message = "Please enter a valid Phone Number.")
	private String phone;
	private String role;
	@NotBlank(message = "Invalid Lastname: Empty Lastname")
	@Size(min = 3, max = 20, message = "Invalid Lastname: Must be of 3 - 20 characters")
	private String lastName;
	@Email(message = "Invalid Email")
	@NotBlank(message = "Invalid Email: Empty Email")
	private String email;
	@JsonIgnore private Set appovesForIdApprover = new HashSet(0);
	@JsonIgnore private Set registerProjects = new HashSet(0);
	@JsonIgnore private Set appovesForIdUser = new HashSet(0);
	@JsonIgnore private Set followProjects = new HashSet(0);
	@JsonIgnore private Set donateDetails = new HashSet(0);
	private Set managers = new HashSet(0);

	public User() {
	}

	public User(String idUser, String fristName, String password, int age, String address, String phone, String role,
			String lastName, String email) {
		this.idUser = idUser;
		this.fristName = fristName;
		this.password = password;
		this.age = age;
		this.address = address;
		this.phone = phone;
		this.role = role;
		this.lastName = lastName;
		this.email = email;
	}

	public User(String idUser, String fristName, String password, int age, String address, String phone, String role,
			String lastName, String email, Set appovesForIdApprover, Set registerProjects, Set appovesForIdUser,
			Set followProjects, Set donateDetails, Set managers) {
		this.idUser = idUser;
		this.fristName = fristName;
		this.password = password;
		this.age = age;
		this.address = address;
		this.phone = phone;
		this.role = role;
		this.lastName = lastName;
		this.email = email;
		this.appovesForIdApprover = appovesForIdApprover;
		this.registerProjects = registerProjects;
		this.appovesForIdUser = appovesForIdUser;
		this.followProjects = followProjects;
		this.donateDetails = donateDetails;
		this.managers = managers;
	}

	public String getIdUser() {
		return this.idUser;
	}

	public void setIdUser(String idUser) {
		this.idUser = idUser;
	}

	public String getFristName() {
		return this.fristName;
	}

	public void setFristName(String fristName) {
		this.fristName = fristName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getAppovesForIdApprover() {
		return this.appovesForIdApprover;
	}

	public void setAppovesForIdApprover(Set appovesForIdApprover) {
		this.appovesForIdApprover = appovesForIdApprover;
	}

	public Set getRegisterProjects() {
		return this.registerProjects;
	}

	public void setRegisterProjects(Set registerProjects) {
		this.registerProjects = registerProjects;
	}

	public Set getAppovesForIdUser() {
		return this.appovesForIdUser;
	}

	public void setAppovesForIdUser(Set appovesForIdUser) {
		this.appovesForIdUser = appovesForIdUser;
	}

	public Set getFollowProjects() {
		return this.followProjects;
	}

	public void setFollowProjects(Set followProjects) {
		this.followProjects = followProjects;
	}

	public Set getDonateDetails() {
		return this.donateDetails;
	}

	public void setDonateDetails(Set donateDetails) {
		this.donateDetails = donateDetails;
	}

	public Set getManagers() {
		return this.managers;
	}

	public void setManagers(Set managers) {
		this.managers = managers;
	}

}
